### ISSUE TITLE
[ENHANCEMENT] List all week affixes

### ISSUE THREAD

**Issue by evacfk** [Hovspian/keystones#2]
Not sure if this project is still maintained but I just ran across this. Thought this would be a great feature implementation.

**Describe the solution you'd like**
Would be nice to be able to retrieve affix information. 

!affixes current (shows current affixes)
!affixes next (would show next week)
!affixes March2 (would show week of March 2)

Could also add aliases to shorten to !a

**Additional context**
All weeks affixes are public knowledge so the data is there.
https://www.wowhead.com/guides/shadowlands-season-1-mythic-dungeon-guide-affix-changes

Thanks,
Fareed

**Comment by Hovspian** [comment]
There's already an `!affixes` command, which will list off the affixes for the current week. Additionally, anyone can check affixes of future weeks by also sending the offset. For example, `!affixes 3` will get the affixes for 3 weeks into the future.

As for aliasing `!affixes`, I would prefer not to alias it to `!a` because that could easily be confused as an alias for the `!affix` command.
